import { Article } from '@/types';

export const articles: Article[] = [
  {
    slug: 'reconstitution-101',
    title: 'Reconstitution 101: How to Mix Your Peptides Safely',
    summary: 'A step-by-step guide to reconstituting lyophilized peptides with bacteriostatic water.',
    category: 'safety',
    readTimeMinutes: 5,
    featured: true,
    body: 'Reconstitution is the process of adding bacteriostatic water (BAC water) to a vial of lyophilized (freeze-dried) peptide powder. This guide covers everything you need to know to do it safely and accurately.',
  },
  {
    slug: 'injection-site-rotation',
    title: 'Why Injection Site Rotation Matters',
    summary: 'Rotating injection sites prevents lipodystrophy and ensures consistent absorption.',
    category: 'safety',
    readTimeMinutes: 4,
    featured: false,
    body: 'Using the same injection site repeatedly can lead to tissue damage, lumps, and inconsistent absorption. Learn the best rotation patterns for subcutaneous peptide injections.',
  },
  {
    slug: 'bpc-157-tb-500-stack',
    title: 'BPC-157 + TB-500: The Recovery Stack',
    summary: 'How these two peptides work synergistically for injury recovery and tissue repair.',
    category: 'protocols',
    readTimeMinutes: 6,
    featured: false,
    body: 'BPC-157 and TB-500 are commonly stacked for their complementary mechanisms in tissue repair. BPC-157 promotes angiogenesis while TB-500 upregulates actin for cell migration.',
  },
  {
    slug: 'gh-peptide-protocols',
    title: 'Growth Hormone Peptide Protocols Explained',
    summary: 'Understanding CJC-1295, Ipamorelin, and GHRP combinations for GH optimization.',
    category: 'protocols',
    readTimeMinutes: 7,
    featured: false,
    body: 'Growth hormone secretagogues work by stimulating your pituitary to release more GH naturally. This article covers common stacking protocols and timing strategies.',
  },
  {
    slug: 'peptide-storage-guide',
    title: 'How to Store Your Peptides Properly',
    summary: 'Temperature, light, and handling guidelines to maintain peptide potency.',
    category: 'safety',
    readTimeMinutes: 3,
    featured: false,
    body: 'Peptide storage directly impacts potency and safety. Lyophilized peptides can be stored at room temperature, but reconstituted peptides must be refrigerated and used within 4 weeks.',
  },
  {
    slug: 'nutrition-for-peptides',
    title: 'Nutrition Timing Around Peptide Doses',
    summary: 'What to eat (and when) to maximize peptide effectiveness.',
    category: 'nutrition',
    readTimeMinutes: 5,
    featured: false,
    body: 'Many peptides, especially GH secretagogues, are best taken on an empty stomach. Learn the optimal nutrition timing windows around your peptide protocol.',
  },
  {
    slug: 'sleep-optimization',
    title: 'Sleep Optimization for Recovery',
    summary: 'How quality sleep amplifies the benefits of your peptide protocol.',
    category: 'recovery',
    readTimeMinutes: 5,
    featured: false,
    body: 'Growth hormone is primarily released during deep sleep stages 3 and 4. Optimizing sleep quality can significantly enhance the results of GH peptide protocols.',
  },
  {
    slug: 'glp1-guide',
    title: 'GLP-1 Agonists: Semaglutide, Tirzepatide & Beyond',
    summary: 'A comprehensive look at the new generation of metabolic peptides.',
    category: 'protocols',
    readTimeMinutes: 8,
    featured: true,
    body: 'GLP-1 receptor agonists have revolutionized metabolic health. This guide covers semaglutide, tirzepatide, and retatrutide — their mechanisms, dosing, and what to expect.',
  },
  {
    slug: 'longevity-peptides',
    title: 'Peptides for Longevity: Epitalon, NAD+, and MOTS-c',
    summary: 'Exploring peptides that target aging at the cellular level.',
    category: 'protocols',
    readTimeMinutes: 6,
    featured: false,
    body: 'Longevity-focused peptides work through different mechanisms — from telomerase activation (Epitalon) to mitochondrial optimization (MOTS-c) to cellular repair (NAD+).',
  },
  {
    slug: 'post-injection-recovery',
    title: 'Post-Injection Care & Recovery Tips',
    summary: 'What to do after your injection to minimize discomfort and maximize absorption.',
    category: 'recovery',
    readTimeMinutes: 3,
    featured: false,
    body: 'Proper post-injection care includes gentle pressure on the site, avoiding rubbing, and staying relaxed. These simple steps improve comfort and absorption consistency.',
  },
  {
    slug: 'common-peptide-questions',
    title: 'Top 10 Peptide Questions Answered',
    summary: 'Answers to the most frequently asked questions about peptide protocols.',
    category: 'q&a',
    readTimeMinutes: 6,
    featured: false,
    body: 'From "how long until I see results?" to "can I travel with peptides?" — we answer the ten most common questions newcomers have about peptide protocols.',
  },
  {
    slug: 'hydration-and-peptides',
    title: 'Hydration: The Overlooked Factor in Peptide Protocols',
    summary: 'Why proper hydration is critical for peptide absorption and effectiveness.',
    category: 'nutrition',
    readTimeMinutes: 4,
    featured: false,
    body: 'Adequate hydration supports subcutaneous absorption, kidney function, and overall cellular processes that peptides rely on. Most people underestimate how much water they need.',
  },
];
