import { PeptideInfo } from '@/types';

export const peptides: PeptideInfo[] = [
  {
    name: 'BPC-157',
    aliases: ['Body Protection Compound-157'],
    typical_dose_mcg: 250,
    half_life_hours: 4,
    frequency_options: ['twice daily', 'daily'],
    category: 'Recovery',
    common_protocols: ['250mcg 2x/day for 4-6 weeks', '500mcg 1x/day for 4 weeks'],
  },
  {
    name: 'TB-500',
    aliases: ['Thymosin Beta-4'],
    typical_dose_mcg: 2500,
    half_life_hours: 72,
    frequency_options: ['twice weekly', 'weekly'],
    category: 'Recovery',
    common_protocols: ['2.5mg 2x/week loading for 4 weeks', '2.5mg 1x/week maintenance'],
  },
  {
    name: 'CJC-1295 (no DAC)',
    aliases: ['Mod GRF 1-29'],
    typical_dose_mcg: 100,
    half_life_hours: 0.5,
    frequency_options: ['3x daily', 'twice daily', 'daily'],
    category: 'Growth Hormone',
    common_protocols: ['100mcg 3x/day with Ipamorelin', '100mcg before bed'],
  },
  {
    name: 'CJC-1295 (with DAC)',
    aliases: ['CJC-1295 DAC'],
    typical_dose_mcg: 2000,
    half_life_hours: 192,
    frequency_options: ['weekly', 'twice weekly'],
    category: 'Growth Hormone',
    common_protocols: ['2mg 1x/week', '1mg 2x/week'],
  },
  {
    name: 'Ipamorelin',
    aliases: ['Ipam'],
    typical_dose_mcg: 200,
    half_life_hours: 2,
    frequency_options: ['3x daily', 'twice daily', 'daily'],
    category: 'Growth Hormone',
    common_protocols: ['200mcg 3x/day', '300mcg before bed', '200mcg with CJC-1295 no DAC'],
  },
  {
    name: 'GHRP-2',
    aliases: ['Growth Hormone Releasing Peptide 2'],
    typical_dose_mcg: 100,
    half_life_hours: 1.5,
    frequency_options: ['3x daily', 'twice daily', 'daily'],
    category: 'Growth Hormone',
    common_protocols: ['100mcg 3x/day', '200mcg before bed'],
  },
  {
    name: 'GHRP-6',
    aliases: ['Growth Hormone Releasing Peptide 6'],
    typical_dose_mcg: 100,
    half_life_hours: 1.5,
    frequency_options: ['3x daily', 'twice daily', 'daily'],
    category: 'Growth Hormone',
    common_protocols: ['100mcg 3x/day', '100mcg before bed'],
  },
  {
    name: 'GHK-Cu',
    aliases: ['Copper Peptide', 'GHK-Copper'],
    typical_dose_mcg: 200,
    half_life_hours: 12,
    frequency_options: ['daily', 'every other day'],
    category: 'Recovery',
    common_protocols: ['200mcg daily for 4 weeks', '100mcg daily topical'],
  },
  {
    name: 'Epitalon',
    aliases: ['Epithalon', 'Epithalone'],
    typical_dose_mcg: 5000,
    half_life_hours: 6,
    frequency_options: ['daily'],
    category: 'Longevity',
    common_protocols: ['5mg daily for 10 days', '10mg daily for 20 days, 2x/year'],
  },
  {
    name: 'Selank',
    aliases: ['TP-7'],
    typical_dose_mcg: 300,
    half_life_hours: 0.5,
    frequency_options: ['twice daily', 'daily'],
    category: 'Cognitive',
    common_protocols: ['300mcg intranasal 2x/day', '250mcg subQ daily'],
  },
  {
    name: 'Semax',
    aliases: ['ACTH 4-10'],
    typical_dose_mcg: 600,
    half_life_hours: 0.5,
    frequency_options: ['twice daily', 'daily'],
    category: 'Cognitive',
    common_protocols: ['600mcg intranasal daily', '200mcg intranasal 3x/day'],
  },
  {
    name: 'PT-141',
    aliases: ['Bremelanotide'],
    typical_dose_mcg: 1750,
    half_life_hours: 4,
    frequency_options: ['as needed'],
    category: 'Sexual Health',
    common_protocols: ['1.75mg as needed, max 1x/day', '500mcg starting dose, titrate up'],
  },
  {
    name: 'AOD-9604',
    aliases: ['Anti-Obesity Drug 9604'],
    typical_dose_mcg: 300,
    half_life_hours: 1,
    frequency_options: ['daily'],
    category: 'Body Composition',
    common_protocols: ['300mcg daily fasted', '250mcg daily for 12 weeks'],
  },
  {
    name: 'MK-677',
    aliases: ['Ibutamoren'],
    typical_dose_mcg: 25000,
    half_life_hours: 24,
    frequency_options: ['daily'],
    category: 'Growth Hormone',
    common_protocols: ['25mg oral daily', '12.5mg daily for beginners'],
  },
  {
    name: 'NAD+',
    aliases: ['Nicotinamide Adenine Dinucleotide'],
    typical_dose_mcg: 100000,
    half_life_hours: 4,
    frequency_options: ['daily', 'weekly'],
    category: 'Longevity',
    common_protocols: ['100mg subQ daily', '250mg IV weekly'],
  },
  {
    name: 'Tirzepatide',
    aliases: ['Mounjaro', 'Zepbound'],
    typical_dose_mcg: 2500,
    half_life_hours: 120,
    frequency_options: ['weekly'],
    category: 'Body Composition',
    common_protocols: ['2.5mg weekly, titrate up monthly', '5mg weekly maintenance'],
  },
  {
    name: 'Semaglutide',
    aliases: ['Ozempic', 'Wegovy'],
    typical_dose_mcg: 250,
    half_life_hours: 168,
    frequency_options: ['weekly'],
    category: 'Body Composition',
    common_protocols: ['0.25mg weekly for 4 weeks, then titrate', '1mg weekly maintenance'],
  },
  {
    name: 'Retatrutide',
    aliases: ['LY-3437943', 'Reta'],
    typical_dose_mcg: 1000,
    half_life_hours: 144,
    frequency_options: ['weekly'],
    category: 'Body Composition',
    common_protocols: ['1mg weekly, titrate monthly', '4mg weekly maintenance'],
  },
  {
    name: 'MOTS-c',
    aliases: ['Mitochondrial ORF of 12S rRNA Type-C'],
    typical_dose_mcg: 5000,
    half_life_hours: 12,
    frequency_options: ['daily', '3x weekly'],
    category: 'Longevity',
    common_protocols: ['5mg subQ daily for 2 weeks', '5mg 3x/week maintenance'],
  },
  {
    name: 'Tesamorelin',
    aliases: ['Egrifta'],
    typical_dose_mcg: 2000,
    half_life_hours: 0.5,
    frequency_options: ['daily'],
    category: 'Growth Hormone',
    common_protocols: ['2mg subQ daily', '1mg daily before bed'],
  },
];
