export interface Tip {
  id: number;
  text: string;
  personality: 'calm' | 'hype' | 'nerdy';
}

export const tips: Tip[] = [
  // CALM (1–30)
  { id: 1, text: 'Consistency matters more than perfection. Show up for yourself today.', personality: 'calm' },
  { id: 2, text: 'Rotate your injection sites to give tissue time to recover.', personality: 'calm' },
  { id: 3, text: 'Hydration supports peptide absorption. Drink a glass of water with your dose.', personality: 'calm' },
  { id: 4, text: 'Store your reconstituted peptides in the fridge — they\'re sensitive to heat.', personality: 'calm' },
  { id: 5, text: 'A steady routine builds steady results. Trust the process.', personality: 'calm' },
  { id: 6, text: 'Take a deep breath before your injection. Tension makes it harder.', personality: 'calm' },
  { id: 7, text: 'Sleep is the foundation of recovery. Prioritize 7-9 hours tonight.', personality: 'calm' },
  { id: 8, text: 'Small improvements compound over time. Be patient with your body.', personality: 'calm' },
  { id: 9, text: 'Check your vial for particles or discoloration before each dose.', personality: 'calm' },
  { id: 10, text: 'Your body does its best repair work while you sleep. Rest well.', personality: 'calm' },
  { id: 11, text: 'Log your doses — it helps you spot patterns over time.', personality: 'calm' },
  { id: 12, text: 'Take your peptides at the same time each day for best results.', personality: 'calm' },
  { id: 13, text: 'BAC water keeps reconstituted peptides stable for up to 4 weeks.', personality: 'calm' },
  { id: 14, text: 'Listen to your body. If something feels off, pause and assess.', personality: 'calm' },
  { id: 15, text: 'A good protocol is one you can stick to. Keep it simple.', personality: 'calm' },
  { id: 16, text: 'Clean the vial top with alcohol before each draw.', personality: 'calm' },
  { id: 17, text: 'Progress isn\'t always visible day-to-day. Zoom out and see how far you\'ve come.', personality: 'calm' },
  { id: 18, text: 'Warm the syringe in your hand for 30 seconds before injecting.', personality: 'calm' },
  { id: 19, text: 'Recovery days are just as important as active days.', personality: 'calm' },
  { id: 20, text: 'Keep your peptides away from direct sunlight.', personality: 'calm' },
  { id: 21, text: 'Your streak matters less than your intention. Keep going.', personality: 'calm' },
  { id: 22, text: 'Use insulin syringes (U-100) for peptide injections — they\'re the most accurate.', personality: 'calm' },
  { id: 23, text: 'Pair your protocol with good nutrition for the best outcomes.', personality: 'calm' },
  { id: 24, text: 'Subcutaneous injections work best in the belly or thigh area.', personality: 'calm' },
  { id: 25, text: 'Don\'t rush. A mindful approach leads to better long-term habits.', personality: 'calm' },
  { id: 26, text: 'Some peptides work best on an empty stomach. Check your protocol.', personality: 'calm' },
  { id: 27, text: 'Track how you feel, not just what you inject. Notes matter.', personality: 'calm' },
  { id: 28, text: 'Peptides degrade with repeated freeze-thaw cycles. Reconstitute only what you need.', personality: 'calm' },
  { id: 29, text: 'Every dose is a step toward your goals. You\'re doing great.', personality: 'calm' },
  { id: 30, text: 'Allow 28 days before judging results. Give your protocol time to work.', personality: 'calm' },

  // HYPE (31–60)
  { id: 31, text: 'LET\'S GO! Another day, another dose. You\'re building something amazing!', personality: 'hype' },
  { id: 32, text: 'Streak check! Keep that fire burning — consistency is your superpower!', personality: 'hype' },
  { id: 33, text: 'You showed up today. That\'s 90% of the battle right there!', personality: 'hype' },
  { id: 34, text: 'Your future self is going to thank you for sticking with this!', personality: 'hype' },
  { id: 35, text: 'Elite athletes track everything. You\'re thinking like a pro!', personality: 'hype' },
  { id: 36, text: 'New day, new gains! Your protocol is working while you sleep!', personality: 'hype' },
  { id: 37, text: 'Rotate those sites like a BOSS. Your tissue will love you for it!', personality: 'hype' },
  { id: 38, text: 'Hydrate like your life depends on it — because your gains do!', personality: 'hype' },
  { id: 39, text: 'That injection? Took 5 seconds. Those results? Last a lifetime!', personality: 'hype' },
  { id: 40, text: 'You\'re not just taking peptides, you\'re investing in your future!', personality: 'hype' },
  { id: 41, text: 'Look at that streak! You\'re absolutely crushing it right now!', personality: 'hype' },
  { id: 42, text: 'The compound effect is REAL. Every dose stacks on the last!', personality: 'hype' },
  { id: 43, text: 'Recovery isn\'t passive — you\'re actively rebuilding. Respect the process!', personality: 'hype' },
  { id: 44, text: 'Morning dose? DONE. You\'re already ahead of 99% of people today!', personality: 'hype' },
  { id: 45, text: 'Your body is a machine. You\'re giving it premium fuel!', personality: 'hype' },
  { id: 46, text: 'Discipline + Science = Results. You\'ve got both covered!', personality: 'hype' },
  { id: 47, text: 'That log entry? Pure accountability. Champions track their progress!', personality: 'hype' },
  { id: 48, text: 'You\'re literally optimizing at the molecular level. How cool is that?!', personality: 'hype' },
  { id: 49, text: 'Sleep hard, recover harder. Your body is doing incredible work tonight!', personality: 'hype' },
  { id: 50, text: 'Another week of consistency. You\'re building an unbreakable habit!', personality: 'hype' },
  { id: 51, text: 'The best part? You\'re only getting started. Imagine 3 months from now!', personality: 'hype' },
  { id: 52, text: 'Pain from the injection is temporary. The results are forever!', personality: 'hype' },
  { id: 53, text: 'You\'re not following the crowd. You\'re leading your own protocol!', personality: 'hype' },
  { id: 54, text: 'BOOM! Dose logged! Another W in the books!', personality: 'hype' },
  { id: 55, text: 'Think about where you were a month ago. Look at you now!', personality: 'hype' },
  { id: 56, text: 'Your dedication is INSANE. Most people quit — you keep showing up!', personality: 'hype' },
  { id: 57, text: 'Rest day? Your peptides are still working! 24/7 optimization!', personality: 'hype' },
  { id: 58, text: 'That calculator? Use it! Precision dosing = maximum results!', personality: 'hype' },
  { id: 59, text: 'You\'re not just hoping for results — you\'re engineering them!', personality: 'hype' },
  { id: 60, text: 'Peptide protocol ON POINT. You should be proud of yourself!', personality: 'hype' },

  // NERDY (61–90)
  { id: 61, text: 'BPC-157 promotes angiogenesis via the VEGF pathway. Fascinating stuff.', personality: 'nerdy' },
  { id: 62, text: 'Subcutaneous absorption follows first-order kinetics — peak levels in 15-30 min.', personality: 'nerdy' },
  { id: 63, text: 'Fun fact: peptides are chains of 2-50 amino acids. Proteins are 50+.', personality: 'nerdy' },
  { id: 64, text: 'Ipamorelin selectively stimulates GH without significantly raising cortisol or prolactin.', personality: 'nerdy' },
  { id: 65, text: 'Half-life determines dosing frequency. Shorter half-life = more frequent doses.', personality: 'nerdy' },
  { id: 66, text: 'BAC water (0.9% benzyl alcohol) acts as a bacteriostatic preservative.', personality: 'nerdy' },
  { id: 67, text: 'CJC-1295 with DAC has a half-life of ~8 days due to drug affinity complex binding.', personality: 'nerdy' },
  { id: 68, text: 'Reconstitution math: (mg in vial × 1000) ÷ mL water = mcg per mL.', personality: 'nerdy' },
  { id: 69, text: 'GH pulses follow a circadian rhythm — highest during deep sleep phases 3 and 4.', personality: 'nerdy' },
  { id: 70, text: 'TB-500 upregulates actin, which is involved in cell migration and wound healing.', personality: 'nerdy' },
  { id: 71, text: 'Epitalon activates telomerase, which may help maintain chromosomal integrity.', personality: 'nerdy' },
  { id: 72, text: 'U-100 syringes: 1 unit = 0.01 mL. So 10 units = 0.1 mL precisely.', personality: 'nerdy' },
  { id: 73, text: 'Semaglutide acts on GLP-1 receptors, slowing gastric emptying and reducing appetite.', personality: 'nerdy' },
  { id: 74, text: 'MOTS-c is a mitochondrial-derived peptide that enhances AMPK pathway activation.', personality: 'nerdy' },
  { id: 75, text: 'Selank modulates IL-6 and affects the balance of T-helper cell subtypes.', personality: 'nerdy' },
  { id: 76, text: 'Lyophilized (freeze-dried) peptides are stable at room temp. Reconstituted = fridge.', personality: 'nerdy' },
  { id: 77, text: 'Tirzepatide is a dual GIP/GLP-1 receptor agonist — that\'s why it\'s so effective.', personality: 'nerdy' },
  { id: 78, text: 'The \'no DAC\' variant of CJC-1295 mimics natural GH pulsatility more closely.', personality: 'nerdy' },
  { id: 79, text: 'GHK-Cu increases collagen and glycosaminoglycan synthesis in skin fibroblasts.', personality: 'nerdy' },
  { id: 80, text: 'PT-141 works via melanocortin-4 receptor activation in the hypothalamus.', personality: 'nerdy' },
  { id: 81, text: 'AOD-9604 is a modified fragment of human growth hormone (amino acids 177-191).', personality: 'nerdy' },
  { id: 82, text: 'Tesamorelin is a GHRH analog that stimulates pituitary GH release physiologically.', personality: 'nerdy' },
  { id: 83, text: 'Insulin syringes use dead-space-free design to minimize peptide waste.', personality: 'nerdy' },
  { id: 84, text: 'Semax is a synthetic analog of ACTH(4-10) with nootropic properties.', personality: 'nerdy' },
  { id: 85, text: 'NAD+ is a cofactor in over 500 enzymatic reactions in the human body.', personality: 'nerdy' },
  { id: 86, text: 'Retatrutide is a triple agonist: GLP-1, GIP, and glucagon receptors.', personality: 'nerdy' },
  { id: 87, text: 'Peptide bonds form via dehydration synthesis between amino and carboxyl groups.', personality: 'nerdy' },
  { id: 88, text: 'MK-677 isn\'t a peptide — it\'s a non-peptide ghrelin mimetic (oral bioavailable).', personality: 'nerdy' },
  { id: 89, text: 'GHRP-2 has the strongest GH release of the GHRP family, but may raise cortisol.', personality: 'nerdy' },
  { id: 90, text: 'Bioavailability of subQ peptides is typically 65-85% compared to IV administration.', personality: 'nerdy' },
];
